<a href="https://colab.research.google.com/github/Nishanta04/SQL/blob/main/SQL_Queries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Setup
Correct the error and run this cell first to import required libraries and define the helper function.

In [ ]:
import sqlite3
import pandas as pd
from tabulate import tabulate

conn = sqlite3.connect("rentio.db")
cursor = conn.cursor()

def run_sql(query):
    return pd.read_sql_query(query, conn)

In [ ]:
cursor.executescript("""
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS store;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS film_category;

CREATE TABLE category (
    category_id INTEGER PRIMARY KEY,
    name TEXT,
    last_update TEXT
);

CREATE TABLE film (
    film_id INTEGER PRIMARY KEY,
    title TEXT,
    length INTEGER,
    release_year INTEGER,
    rating TEXT
);

CREATE TABLE store (
    store_id INTEGER PRIMARY KEY,
    manager_staff_id INTEGER,
    address_id INTEGER,
    last_update TEXT
);

CREATE TABLE staff (
    staff_id INTEGER PRIMARY KEY,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    active INTEGER,
    address_id INTEGER
);

CREATE TABLE film_category (
    film_id INTEGER,
    category_id INTEGER
);
""")

conn.commit() # It saves the DB from RAM to HardDisk

In [ ]:
cursor.executemany(
    "INSERT INTO category VALUES (?, ?, ?)",
    [
        (1, "Action", "2006-02-15 05:03:42"),
        (2, "Animation", "2006-02-15 05:03:42"),
        (3, "Horror", "2006-02-15 05:03:42"),
        (4, "Music", "2006-02-15 05:03:42"),
        (5, "Sci-Fi", "2006-02-15 05:03:42"),
    ]
)

cursor.executemany(
    "INSERT INTO film VALUES (?, ?, ?, ?, ?)",
    [
        (1, "Iron Man", 126, 2008, "PG-13"),
        (2, "The Incredible Hulk", 112, 2008, "PG-13"),
        (3, "Iron Man 2", 124, 2010, "PG-13"),
        (4, "Thor", 115, 2011, "PG-13"),
        (5, "Captain America: The First Avenger", 124, 2011, "PG-13"),
        (6, "The Avengers", 143, 2012, "PG-13"),
        (7, "Iron Man 3", 130, 2013, "PG-13"),
        (8, "Thor: The Dark World", 112, 2013, "PG-13"),
        (9, "Captain America: The Winter Soldier", 136, 2014, "PG-13"),
        (10, "Guardians of the Galaxy", 121, 2014, "PG-13"),
    ]
)

cursor.executemany(
    "INSERT INTO film_category VALUES (?, ?)",
    [
        (1, 1),
        (2, 2),
        (3, 2),
        (4, 4),
        (5, 4),
        (6, 5),
        (7, 1),
        (8, 5),
        (9, 5),
        (10, 1),
    ]
)

cursor.executemany(
    "INSERT INTO store VALUES (?, ?, ?, ?)",
    [
        (1, 1, 1, "2006-02-15 05:03:42"),
        (2, 2, 2, "2006-02-15 05:03:43"),
    ]
)

cursor.executemany(
    "INSERT INTO staff VALUES (?, ?, ?, ?, ?, ?)",
    [
        (1, "Mike", "Hillyer", "james.monroe@examplepetstore.com", 1, 1),
        (2, "Jon", "Stephens", "john.c.calhoun@examplepetstore.com", 1, 2),
    ]
)
conn.commit()

## Question 1: Basic Data Retrieval
Write an SQL query to display all columns from the `film` table.

In [ ]:
# TODO: Write your SQL query here
run_sql("""
SELECT * FROM film
""")

   film_id                                title  length  release_year rating
0        1                             Iron Man     126          2008  PG-13
1        2                  The Incredible Hulk     112          2008  PG-13
2        3                           Iron Man 2     124          2010  PG-13
3        4                                 Thor     115          2011  PG-13
4        5   Captain America: The First Avenger     124          2011  PG-13
5        6                         The Avengers     143          2012  PG-13
6        7                           Iron Man 3     130          2013  PG-13
7        8                 Thor: The Dark World     112          2013  PG-13
8        9  Captain America: The Winter Soldier     136          2014  PG-13
9       10              Guardians of the Galaxy     121          2014  PG-13

## Question 2: Filtering Records
Retrieve the title and rating of all films with rating `PG` or `PG-13`.

In [ ]:
# TODO
run_sql("""
SELECT title, rating FROM film
WHERE rating = 'PG' OR rating = 'PG-13'
""")

                                 title rating
0                             Iron Man  PG-13
1                  The Incredible Hulk  PG-13
2                           Iron Man 2  PG-13
3                                 Thor  PG-13
4   Captain America: The First Avenger  PG-13
5                         The Avengers  PG-13
6                           Iron Man 3  PG-13
7                 Thor: The Dark World  PG-13
8  Captain America: The Winter Soldier  PG-13
9              Guardians of the Galaxy  PG-13

## Question 3: Sorting and Limiting Results
List all films ordered by length (descending). Display only the top two longest films.

In [ ]:
# TODO
run_sql("""
SELECT * FROM film
ORDER BY length DESC
LIMIT 2
""")

   film_id                                title  length  release_year rating
0        6                         The Avengers     143          2012  PG-13
1        9  Captain America: The Winter Soldier     136          2014  PG-13

## Question 4: Aggregate Functions
Calculate the average length of all films. Rename the column as `average_film_length`.

In [ ]:
# TODO
run_sql("""
SELECT AVG(length) AS average_film_length FROM film
""")

   average_film_length
0                124.3

## Question 5: Joining Tables
Display each film title along with its category name.

In [ ]:
# TODO
run_sql("""
SELECT film.title, category.name AS category_name
FROM film
JOIN film_category ON film.film_id = film_category.film_id
JOIN category ON film_category.category_id = category.category_id
""")

                                 title category_name
0                             Iron Man        Action
1                  The Incredible Hulk     Animation
2                           Iron Man 2     Animation
3                                 Thor         Music
4   Captain America: The First Avenger         Music
5                         The Avengers        Sci-Fi
6                           Iron Man 3        Action
7                 Thor: The Dark World        Sci-Fi
8  Captain America: The Winter Soldier        Sci-Fi
9              Guardians of the Galaxy        Action

## Question 6: GROUP BY and COUNT
Show the number of films in each category, sorted from highest to lowest count.

In [ ]:
# TODO
run_sql("""
SELECT category.name AS category_name, COUNT(film.film_id) AS film_count
FROM category
JOIN film_category ON category.category_id = film_category.category_id
JOIN film ON film_category.film_id = film.film_id
GROUP BY category.name
ORDER BY film_count DESC
""")

  category_name  film_count
0        Sci-Fi           3
1        Action           3
2         Music           2
3     Animation           2

## Question 7: Handling Duplicate Data
Display distinct category names only.

In [ ]:
# TODO
run_sql("""
SELECT DISTINCT category.name AS category_name
FROM category
JOIN film_category ON category.category_id = film_category.category_id
""")

  category_name
0        Action
1     Animation
2         Music
3        Sci-Fi

## Question 8: Conditional Logic
Display film title and classify films as `Long Film` or `Short Film`.

In [ ]:
# TODO
run_sql("""
SELECT title,
CASE
    WHEN length > 120 THEN 'Long Film'
    ELSE 'Short Film'
END AS film_type
FROM film
""")

                                 title   film_type
0                             Iron Man   Long Film
1                  The Incredible Hulk  Short Film
2                           Iron Man 2   Long Film
3                                 Thor  Short Film
4   Captain America: The First Avenger   Long Film
5                         The Avengers   Long Film
6                           Iron Man 3   Long Film
7                 Thor: The Dark World  Short Film
8  Captain America: The Winter Soldier   Long Film
9              Guardians of the Galaxy   Long Film

## Question 9: Multi-Table Query
Display Store ID, Manager’s full name, and Manager’s email.

In [ ]:
# TODO
run_sql("""
SELECT store.store_id, staff.first_name || ' ' || staff.last_name AS manager_name, staff.email
FROM store
JOIN staff ON store.manager_staff_id = staff.staff_id
""")

   store_id  manager_name                               email
0         1  Mike Hillyer    james.monroe@examplepetstore.com
1         2  Jon Stephens  john.c.calhoun@examplepetstore.com

## Question 10: Data Validation Query
Identify categories that have no films assigned to them.

In [ ]:
# TODO
run_sql("""
SELECT category.name AS category_name
FROM category
LEFT JOIN film_category ON category.category_id = film_category.category_id
WHERE film_category.film_id IS NULL
""")

  category_name
0        Horror

## Challenge 1 (Optional)
Retrieve all film data and display it using `tabulate`.

In [ ]:
# TODO
df = run_sql("""
SELECT * FROM film
""")
print(tabulate(df, headers='keys', tablefmt='psql', showindex=False))

+-----------+-------------------------------------+----------+----------------+----------+
|   film_id | title                               |   length |   release_year | rating   |
|-----------+-------------------------------------+----------+----------------+----------|
|         1 | Iron Man                            |      126 |           2008 | PG-13    |
|         2 | The Incredible Hulk                 |      112 |           2008 | PG-13    |
|         3 | Iron Man 2                          |      124 |           2010 | PG-13    |
|         4 | Thor                                |      115 |           2011 | PG-13    |
|         5 | Captain America: The First Avenger  |      124 |           2011 | PG-13    |
|         6 | The Avengers                        |      143 |           2012 | PG-13    |
|         7 | Iron Man 3                          |      130 |           2013 | PG-13    |
|         8 | Thor: The Dark World                |      112 |           2013 | PG-13    |
|         9 | Captain America: The Winter Soldier |      136 |           2014 | PG-13    |
|        10 | Guardians of the Galaxy             |      121 |           2014 | PG-13    |
+-----------+-------------------------------------+----------+----------------+----------+